const cfg=window.APP_CONFIG||{};const configured=cfg.SUPABASE_URL?.startsWith("https://")&&!cfg.SUPABASE_ANON_KEY?.startsWith("COLE_");const db=configured?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let gifts=[],category="Todos";const grid=document.querySelector("#giftGrid"),filters=document.querySelector("#categoryFilters"),only=document.querySelector("#onlyAvailable"),toast=document.querySelector("#toast"),modalRoot=document.querySelector("#modalRoot");
function notify(text,error=false){toast.textContent=text;toast.style.background=error?"#7c3f38":"#263127";toast.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.hidden=true,5000)}
function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
async function load(){if(!db){grid.innerHTML='<div class="empty">O site ainda precisa ser conectado ao banco. Consulte o arquivo LEIA-ME.md.</div>';return}const {data,error}=await db.rpc("get_gift_catalog");if(error){grid.innerHTML='<div class="empty">Não foi possível carregar a lista agora.</div>';console.error(error);return}gifts=data||[];drawFilters();draw()}
function drawFilters(){const cats=["Todos",...new Set(gifts.map(g=>g.category))];filters.innerHTML=cats.map(c=>`<button class="${c===category?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join("");filters.querySelectorAll("button").forEach(b=>b.onclick=()=>{category=b.dataset.cat;drawFilters();draw()})}
function draw(){const list=gifts.filter(g=>(category==="Todos"||g.category===category)&&(!only.checked||g.available>0));if(!list.length){grid.innerHTML='<div class="empty">Nenhum presente disponível neste filtro.</div>';return}grid.innerHTML=list.map(g=>{const pct=Math.round(((g.desired-g.available)/g.desired)*100);return `<article class="card"><div class="photo">${g.image_url?`<img src="${esc(g.image_url)}" alt="${esc(g.name)}">`:'<div class="placeholder"><span>⌂</span><small>FOTO EM BREVE</small></div>'}<span class="status">${g.available?'Disponível':'Presente escolhido 💛'}</span></div><div class="card-body"><span class="category">${esc(g.category)}</span><h3>${esc(g.name)}</h3><p>${esc(g.description||"")}</p><div class="progress"><div><span>${g.available?`Faltam ${g.available} de ${g.desired}`:`Completo — ${g.desired} de ${g.desired}`}</span><span>${pct}%</span></div><i class="bar"><b style="width:${pct}%"></b></i></div><div class="actions">${g.available?`<button class="btn primary reserve" data-id="${g.id}">Quero presentear</button>`:""}${g.purchase_url?`<a class="btn secondary" href="${esc(g.purchase_url)}" target="_blank" rel="noopener">Comprar online ↗</a>`:""}</div>${!g.purchase_url?'<small class="hint">Você pode procurar este item na loja que preferir.</small>':""}</div></article>`}).join("");grid.querySelectorAll(".reserve").forEach(b=>b.onclick=()=>openReserve(Number(b.dataset.id)))}
function openReserve(id){const g=gifts.find(x=>x.id===id);modalRoot.innerHTML=`<div class="shade"><div class="modal" role="dialog" aria-modal="true"><button class="close" aria-label="Fechar">×</button><span class="eyebrow">QUE ALEGRIA!</span><h2>Quero presentear</h2><p>Você escolheu <strong>${esc(g.name)}</strong>. A compra pode ser feita onde preferir.</p><form id="reserveForm"><input type="hidden" name="gift_id" value="${g.id}"><label>Seu nome<input name="name" maxlength="100" required autofocus placeholder="Digite seu nome"></label>${g.available>1?`<label>Quantidade<select name="quantity">${Array.from({length:g.available},(_,i)=>`<option>${i+1}</option>`).join("")}</select></label>`:'<input type="hidden" name="quantity" value="1">'}<label>Telefone ou WhatsApp (opcional)<input name="phone" maxlength="40" placeholder="(00) 00000-0000"></label><label>Mensagem (opcional)<textarea name="message" maxlength="1000" rows="3" placeholder="Quer deixar um recadinho?"></textarea></label><button class="btn primary" type="submit">Confirmar reserva</button></form></div></div>`;modalRoot.querySelector(".close").onclick=closeModal;modalRoot.querySelector(".shade").onclick=e=>{if(e.target.classList.contains("shade"))closeModal()};modalRoot.querySelector("form").onsubmit=reserve}
function closeModal(){modalRoot.innerHTML=""}
async function reserve(e){e.preventDefault();const f=new FormData(e.currentTarget),button=e.currentTarget.querySelector("button");button.disabled=true;button.textContent="Confirmando…";const {data,error}=await db.rpc("reserve_gift",{p_gift_id:Number(f.get("gift_id")),p_quantity:Number(f.get("quantity")),p_name:f.get("name"),p_phone:f.get("phone")||"",p_message:f.get("message")||""});if(error||!data?.ok){notify(data?.error||"Este presente acabou de ser escolhido. Atualizei a disponibilidade.",true);closeModal();await load();return}closeModal();notify("Que carinho! 💛 Seu presente foi reservado. Muito obrigada!");await load()}
document.querySelector("#messageForm").onsubmit=async e=>{e.preventDefault();if(!db)return notify("Configure o banco antes de enviar mensagens.",true);const f=new FormData(e.currentTarget),button=e.currentTarget.querySelector("button");button.disabled=true;const {data,error}=await db.rpc("submit_message",{p_name:f.get("name"),p_message:f.get("message")});button.disabled=false;if(error||!data?.ok)return notify("Não foi possível enviar o recadinho.",true);e.currentTarget.reset();notify("Recadinho enviado com carinho. Muito obrigada! 💛")};only.onchange=draw;load();
